"""added role to user table

Revision ID: 82dd04101ba6
Revises: ee05c9649b7b
Create Date: 2026-06-25 20:06:17.063274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dd04101ba6'
down_revision: Union[str, Sequence[str], None] = 'ee05c9649b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum('ADMIN', 'USER', 'MODERATOR', name='userrole')
    userrole_enum.create(op.get_bind())
    op.add_column('notes_users', sa.Column('role', sa.Enum('ADMIN', 'USER', 'MODERATOR', name='userrole'), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes_users', 'role')
    op.drop_constraint(None, 'notes', type_='unique')
    # ### end Alembic commands ###
